on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: asdf-vm/actions/install@v3
      with:
        tool_versions: |
          action-validator 0.5.1
    - run: action-validator --verbose ./action.yml

  test-linux:
    needs:
    - lint
    runs-on: ubuntu-latest
    env:
      MC_USER: user
      MC_PASS: minio123
    services:
      minio:
        image: fclairamb/minio-github-actions
        env:
          MINIO_ROOT_USER: user
          MINIO_ROOT_PASSWORD: minio123
        ports:
        - 9001:9000
    steps:
    - uses: actions/checkout@v4
    - uses: ./
    - run: mc alias set minio http://127.0.0.1:9001 $MC_USER $MC_PASS
    - run: mc mb minio/test
    - run: mc cp action.yml minio/test/
    - run: mc ls minio/test

  test-macos:
    needs:
    - lint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Start MinIO container
      run: |
        brew install minio/stable/minio
        mkdir -p ~/.minio/data
        export MINIO_ROOT_USER=user
        export MINIO_ROOT_PASSWORD=minio123
        minio server ~/.minio/data --console-address ":9001" &
        sleep 5
    - uses: ./
      with:
        platform: darwin
    - run: mc alias set minio http://127.0.0.1:9000 user minio123
    - run: mc mb minio/test
    - run: mc cp action.yml minio/test/
    - run: mc ls minio/test

  test-windows:
    needs:
    - lint
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Start MinIO container
      shell: pwsh
      run: |
        mkdir -p $HOME/minio-data
        docker run -d -p 9000:9000 -p 9001:9001 --name minio `
          -e "MINIO_ROOT_USER=user" `
          -e "MINIO_ROOT_PASSWORD=minio123" `
          -v "$HOME/minio-data:/data" `
          minio/minio server /data --console-address ":9001"
        Start-Sleep -s 5
    - uses: ./
      with:
        platform: windows
    - shell: pwsh
      run: mc.exe alias set minio http://127.0.0.1:9000 user minio123
    - shell: pwsh
      run: mc.exe mb minio/test
    - shell: pwsh
      run: mc.exe cp action.yml minio/test/
    - shell: pwsh
      run: mc.exe ls minio/test

  test-inputs:
    needs:
    - lint
    runs-on: ubuntu-latest
    services:
      minio:
        image: fclairamb/minio-github-actions
        env:
          MINIO_ROOT_USER: user
          MINIO_ROOT_PASSWORD: minio123
        ports:
        - 9002:9000
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        alias-name: example
        alias-url: http://127.0.0.1:9002
        alias-access-key: user
        alias-secret-key: minio123
    - run: mc mb example/test-bucket
    - run: mc ls example/test-bucket
